#include <stm32f0xx.h>
#include "mcu_init.h"

void io_init(void)
{
    RCC->AHBENR  = RCC_AHBENR_VALUE;
#ifdef RCC_AHBENR_VALUE
    RCC->AHBENR = RCC_AHBENR_VALUE;
#endif
#ifdef RCC_APB2ENR_VALUE
    RCC->APB2ENR = RCC_APB2ENR_VALUE;
#endif
#ifdef RCC_APB1ENR_VALUE
    RCC->APB1ENR = RCC_APB1ENR_VALUE;
#endif
    // GPIO A
#ifdef GPIOA_AFR0_VALUE
    GPIOA->AFR[0]   = GPIOA_AFR0_VALUE;
#endif
#ifdef GPIOA_AFR1_VALUE
    GPIOA->AFR[1]   = GPIOA_AFR1_VALUE;
#endif
#ifdef GPIOA_MODER_VALUE
    GPIOA->MODER    = GPIOA_MODER_VALUE;
#endif
#ifdef GPIOA_OTYPER_VALUE
    GPIOA->OTYPER   = GPIOA_OTYPER_VALUE;
#endif
#ifdef GPIOA_OSPEEDR_VALUE
    GPIOA->OSPEEDR  = GPIOA_OSPEEDR_VALUE;
#endif
#ifdef GPIOA_PUPDR_VALUE
    GPIOA->PUPDR    = GPIOA_PUPDR_VALUE;
#endif
#ifdef GPIOA_ODR_VALUE
    GPIOA->ODR=GPIOA_ODR_VALUE;
#endif
    // GPIO B
#ifdef GPIOB_AFR0_VALUE
    GPIOB->AFR[0]   = GPIOB_AFR0_VALUE;
#endif
#ifdef GPIOB_AFR1_VALUE
    GPIOB->AFR[1]   = GPIOB_AFR1_VALUE;
#endif
#ifdef GPIOB_MODER_VALUE
    GPIOB->MODER    = GPIOB_MODER_VALUE;
#endif
#ifdef GPIOB_PUPDR_VALUE
    GPIOB->PUPDR    = GPIOB_PUPDR_VALUE;
#endif
#ifdef GPIOB_OTYPER_VALUE
    GPIOB->OTYPER   = GPIOB_OTYPER_VALUE;
#endif
#ifdef GPIOB_OSPEEDR_VALUE
    GPIOB->OSPEEDR  = GPIOB_OSPEEDR_VALUE;
#endif
#ifdef GPIOB_PUPDR_VALUE
    GPIOB->PUPDR    = GPIOB_PUPDR_VALUE;
#endif
    // GPIO C
#ifdef GPIOC_AFR0_VALUE
    GPIOC->AFR[0]   = GPIOC_AFR0_VALUE;
#endif
#ifdef GPIOC_AFR1_VALUE
    GPIOC->AFR[1]   = GPIOC_AFR1_VALUE;
#endif
#ifdef GPIOC_MODER_VALUE
    GPIOC->MODER    = GPIOC_MODER_VALUE;
#endif
#ifdef GPIOC_OTYPER_VALUE
    GPIOC->OTYPER   = GPIOC_OTYPER_VALUE;
#endif
#ifdef GPIOC_OSPEEDR_VALUE
    GPIOC->OSPEEDR  = GPIOC_OSPEEDR_VALUE;
#endif
#ifdef GPIOC_PUPDR_VALUE
    GPIOC->PUPDR    = GPIOC_PUPDR_VALUE;
#endif

    // GPIO F
#ifdef GPIOF_MODER_VALUE
    GPIOF->MODER    = GPIOF_MODER_VALUE;
#endif
#ifdef GPIOF_PUPDR_VALUE
    GPIOF->PUPDR    = GPIOF_PUPDR_VALUE;
#endif


}